branches:
  only:
    - master
    - /^develop.*$/
    - teste
jobs:
 include:
  - stage: modeling
    env:
      - TEST_SUITE=test_gaussianModelBuild
      - TESTE_SUITE=test_multiLayerModelBuild
    script: ./test_travis_docker.sh $TEST_SUITE
  - stage: deploy
    script: echo "TODO deploy"
