/* This file is automatically generated. DO NOT EDIT! */

#ifndef _vfsacrenh_lib_h
#define _vfsacrenh_lib_h


#define Beta_MAX 1
#define Beta_MIN -1
#define Rnip_MAX 2
#define Rnip_MIN 0
#define hMAX 50
#define mMAX 50
#define ITMAX 10000
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <rsf.h>


float sinal(float s);
/*< Função sinal >*/


float gerarNumeroAleatorioEntre0e1();
/*< Função gerar número aleatório entre 0 e 1 >*/


float temperaturaIteracaoVfsa(int iteracao,float fatorDeAmortecimento,float temperaturaInicial);
/*< Função temperatura do algoritmo VFSA >*/


void perturbacaoParametros(float temperatura, float* parametrosPerturbados, float* parametros);
/*< Perturbar os parâmetros da iteração anterior >*/


float fomel(float m, float h, float t0, float v0, float RNIP, float BETA);
/*< Aproximação de tempo de trânsito do CRS não hiperbólico (FOMEL; KAZINNIK, 2013) >*/


float semblance(float m0, float dm, float om, float oh, float dh, float dt, int nt,float t0, float v0,float RNIP, float BETA, float*** t);
/*< Função Semblance >*/

#endif
